# +----------------------------------------------------------------------------------------+
# |    _____   _   _    ___    _____      _____   _   _    ___    _____   _   _   _____    |
# |   |  ___| | | | |  / _ \  |_   _|    |  ___| | \ | |  / _ \  |_   _| | \ | | |  ___|   |
# |   | |     | |_| | | |_| |   | |      | |___  |  \| | | | |_|   | |   |  \| | | |___    |
# |   | |     |  _  | |  _  |   | |      |  ___| |     | | | __    | |   |     | |  ___|   |
# |   | |___  | | | | | | | |   | |      | |___  | |\  | | |_/ |  _| |_  | |\  | | |___    |
# |   |_____| |_| |_| |_| |_|   |_|      |_____| |_| |_|  \____| |_____| |_| |_| |_____|   |
# |                                                                                        |
# |   Автор: SoKnight                                                      Версия: 1.1.0   |
# +----------------------------------------------------------------------------------------+
#
# Настройки чата
chat:
  # Глобальный чат
  global:
    # Формат
    format: "&6[Г] &b%prefix%%sender%%suffix% &7» &r%message%"
    # Префикс сообщения для отправки в глобальный чат
    prefix: "!"
    # Кулдаун отправки сообщений (в секундах)
    # Если -1, то отключено
    cooldown: 5
  # Локальный чат
  local:
    # Формат
    format: "&e[Л] &b%prefix%%sender%%suffix% &7» &r%message%"
    # Дальность локального чата (в блоках)
    radius: 100
    # Кулдаун отправки сообщений (в секундах)
    # Если -1, то отключено
    cooldown: -1
# Серверные сообщения
server-messages:
  # Вход игрока на сервер
  join:
    # Показывать ли сообщение
    show: true
    # Формат сообщения
    format: "&e%player% присоединился к игре."
  # Выход игрока с сервера
  quit:
    # Показывать ли сообщение
    show: true
    # Формат сообщения
    format: "&e%player% покинул игру."
  # Показывать ли в чате сообщения о смертях игроков
  show-deaths: false
# Настройки приватных сообщений
private-messages:
  # Формат личных сообщений в игровом чате
  format: "&2[ЛС] &7[%sender% -> %receiver%] &f%message%"
  # Замена имени Server на другое в личных сообщениях
  name-replacing: "#console"
  # Включена ли функция кликабельности
  clickable: true
  # Сообщение при наведении на текст
  hover-text:
    # Сообщение для отправителя
    sender: "&aНажмите, чтобы отправить другое сообщение"
    # Сообщение для получателя
    receiver: "&aНажмите, чтобы ответить отправителю"
    # Сообщение для получателя, если отправитель - консоль
    by-console: "&cФункция быстрого ответа недоступна"
  # Текст для вставки в поле ввода после клика по тексту
  insertion: "/w %player% "
# Настройки таблиста
tablist:
  # Заголовок таблиста
  header-use: true
  header: " \n &ePlasticCraft \n &fСервер: &bserver \n "
  # Футер таблиста
  footer-use: true
  footer: " \n &fОнлайн: &b%server_online%/%server_max_players% \n "
  # Формат прав для групп
  permission: 'group.%group%'
  # Частота обновления таблиста (в секундах)
  update-frequency: 3
# Настройки оповещений
broadcast:
  # Возврат сообщения из broadcast в консоль, если команда выполнена оттуда
  return: true
  # Формат для сообщений из broadcast
  format: "&c[A] &f%message%"
# Настройки рп-сообщений
roleplay:
  # Настройки локальных сообщений
  local:
    # Кулдаун отправки сообщений (в секундах)
    cooldown: -1
    # Радиус для поиска игроков (в блоках)
    radius: 100
    # Формат сообщений
    format: "&e[Л] &f%sender% %message%"
    # Показывать сообщения в консоли
    show-in-console: true
  # Настройки глобальных сообщений
  global:
    # Кулдаун отправки сообщений (в секундах)
    cooldown: 60
    # Формат сообщений
    format: "&6[Г] &f%sender% %message%"
    # Показывать сообщения в консоли
    show-in-console: true
# Редирект команд с префиксами
command-redirect:
  # Использовать ли это
  enabled: true
  # Префиксы для редиректируемых команд
  prefixes:
  - 'minecraft:'
# Сообщения в результате выполнения команд
messages:
  error-not-permission: "&cНедостаточно прав."
  error-player-not-found: "&cИгрок %player% не найден."
  error-only-for-players: "&cКоманда доступна только игроку."
  error-invalid-syntax: "&cНеверное использование команды. Используйте: %usage%"
  error-unknown-command: "&cПод-команда не найдена. Доступные: reload"
  error-cooldown-command: "&cПодождите ещё %time% сек. перед использованием этой команды."
  error-cooldown-chat: "&cПодождите ещё %time% сек. перед следующей отправкой сообщения в этот чат."
  reload-success: "&fChatEngine перезагружен!"